### ISSUE TITLE
property.php template missing slideshow and more?

### ISSUE THREAD

**Issue by oceandigital** [wp-property/wp-property.github.io#1]
Im not a coder but I do my best. I followed instructions to copy property.php to my theme folder but the output does not show the responsive slideshow and the rest of the page has no styling at all.  Im not sure what other addon shortcodes are not included in the property.php template but if there are other missing things it would be good to have detailed documentation on how to modify the file.

To solve it, I borrowed some code from the Avalon theme:
```
<?php if (function_exists('ud_get_wpp_resp_slideshow')) : ?>
        <div class="<?php wpp_css('property::property_responsive_slideshow', "property_responsive_slideshow_box"); ?>">
          <?php echo do_shortcode('[property_responsive_slideshow slider_type=carousel]'); ?>
        </div>
      <?php elseif (has_post_thumbnail(get_the_ID())) : ?>
        <div class="<?php wpp_css('property::featured_image', "wpp_featured_image"); ?>">
          <a class="fancybox_image" rel="fancybox"
             href="<?php echo wp_get_attachment_url(get_post_thumbnail_id(get_the_ID())); ?>">
            <?php echo get_the_post_thumbnail(get_the_ID()); ?>
          </a>
        </div>
      <?php endif; ?>
```

and inserted it into property.php under:
`<div class="<?php wpp_css('property::entry_content', "entry-content"); ?>">`

My next challenge is to make the list of visible attributes look better. After that I want to find a way to hide the info pop-up on the google map.

**Comment by Mashenka** [comment]
property.php never has a slideshow in itself. Other themes template have as you mentioned.
You could also check this article - https://wp-property.github.io/docs/customizing-templates/

**Comment by oceandigital** [comment]
> property.php never has a slideshow in itself

Why not? It should be so that the slideshow plugin will work. This is why I opened the issue.  You should either include it in property.php or detail how to insert the code manually.  The link you provided does not help at all.

**Comment by Mashenka** [comment]
Each site is individual and everyone want to place the slideshow in its own location when using some custom theme, so we included slideshow only in our themes templates. 

I have updated article, which I sent, with this code, which you could use to insert slideshow to property.php template
echo do_shortcode('[property_responsive_slideshow]'); ?>
